[package]
name = "hnsw_new"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[build]
rustflags = ["-C", "target-cpu=native"]

[lib]
bench = false

[dependencies]
indicatif = "0.17.8"
nohash-hasher = "0.2.0"
rand = "0.8.5"
